### ISSUE TITLE
Change log level for external-secrets and calico

### ISSUE THREAD

**Issue by khalezin** [maddevsio/aws-eks-base#43]
External-secrets service and calico service produce a lot of logs message, we need to change log-level for these services.

**Comment by mglotov** [comment]
For Calico: https://github.com/maddevsio/aws-eks-base/blob/ad56666308fe15419f2e5f2d8812c68fe0c692d3/terraform/layer2-k8s/templates/calico-values.yaml#L27

For external-secrets: https://github.com/maddevsio/aws-eks-base/blob/ad56666308fe15419f2e5f2d8812c68fe0c692d3/terraform/layer2-k8s/templates/external-secrets-values.yaml#L6
