### ISSUE TITLE
Restrict access for EKS endpoint

### ISSUE THREAD

**Issue by halfb00t** [maddevsio/aws-eks-base#9]
First stage: Add security group for public EKS API Endpoint
Second stage: add vpn instance to l1, provide documentation to configure vpn connection, set EKS API Endpoint as private

**Comment by mglotov** [comment]
> First stage: Add security group for public EKS API Endpoint
> Second stage: add vpn instance to l1, provide documentation to configure vpn connection, set EKS API Endpoint as private

1. There is an input variable cluster_endpoint_public_access_cidrs. We can use it to control public access to EKS API endpoint.

From my point of view, we need to have the possibility to switch the EKS endpoint among three states:
1. public
2. public + private
3. private

@halfb00t @p1gmale0n WDYT?
